version: '3.9'

services:
  client.birthday-calendar:
    build: .
    image: client.birthday-calendar.image
    container_name: client.birthday-calendar.container
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
